import json
import matplotlib.pyplot as plt
from finder import Pathfinder # Import your Pathfinder class

def plot_path_in_housing(housing_boundaries, start_node, end_node, path, title, filename):
    """Helper function to plot the housing, shafts, and a given path."""
    
    # Unzip the boundary points for plotting
    bx, by = zip(*housing_boundaries, housing_boundaries[0]) 
    
    plt.figure(figsize=(8, 8))
    # Plot the housing boundary
    plt.plot(bx, by, 'k-', label='Housing Boundary') 
    
    # Plot the start and end shafts
    plt.plot(start_node[0], start_node[1], 'go', markersize=10, label='Input Shaft')
    plt.plot(end_node[0], end_node[1], 'ro', markersize=10, label='Output Shaft')
    
    if path:
        # Unzip the path points for plotting
        px, py = zip(*path)
        plt.plot(px, py, 'b--', label='Generated Path') # Plot the path
        
    plt.title(title)
    plt.xlabel('X Coordinate')
    plt.ylabel('Y Coordinate')
    plt.legend()
    plt.grid(True)
    plt.gca().set_aspect('equal', adjustable='box')
    plt.savefig(filename) # Save the figure to a file
    plt.show()

# --- Main Script ---
if __name__ == "__main__":
    # 1. Define the path to your input JSON file
    # Make sure this file exists and contains a non-convex shape.
    # This is the correct path to your file
    processed_data_path = 'c:\\Users\\Mmdocks\\Desktop\\CODE\\GearboxRL\\GearRL\\data\\intermediate\\simple_rect.json'

    # 2. Load the geometric data for plotting
    with open(processed_data_path, 'r') as f:
        data = json.load(f)['normalized_space']
    boundaries = [tuple(p) for p in data['boundaries']]
    start = tuple(data['input_shaft'].values())
    end = tuple(data['output_shaft'].values())

    # 3. Instantiate your Pathfinder
    finder = Pathfinder()

    # 4. Generate the "Before" picture: The raw A* path
    print("Generating the raw A* path...")
    # Use a small margin to ensure the path is close to the walls
    raw_a_star_path = finder.find_path(processed_data_path, margin=0.1) 
    
    if raw_a_star_path:
        plot_path_in_housing(
            boundaries, start, end, raw_a_star_path,
            'Figure 3.1: Initial Path Generated by A* Algorithm',
            'a_star_path.png'
        )
    else:
        print("Could not find a raw A* path.")

    # 5. Generate the "After" picture: The smoothed centerline path
    print("Generating the smoothed centerline path...")
    smoothed_path = finder.find_centerline_path(processed_data_path)
    
    if smoothed_path:
        plot_path_in_housing(
            boundaries, start, end, smoothed_path,
            'Figure 3.2: Smoothed Centerline Path after Relaxation',
            'smoothed_centerline_path.png'
        )
    else:
        print("Could not find a smoothed path.")